<?php

/**
 * Magento
 *
 * @category   RayPay
 * @package    RayPay
 * @copyright  Copyright (c) 2021 RayPay (https://raypay.ir)
 */
?>

<html>
<meta http-equiv="refresh" content="0; URL=<?php echo $this->getContinueShoppingUrl() ?>">
<body>
<div class="page-head">
    <h3><?php echo $this->__('Error occured') ?></h3>
</div>
<p><?php echo $this->__('Please <a href="%s">continue shopping</a>.', $this->getContinueShoppingUrl()) ?></p>
</body>
</html>
