<?php

/**
 * Magento
 *
 * @category   RayPay
 * @package    RayPay
 * @copyright  Copyright (c) 2021 RayPay (https://raypay.ir)
 */

echo $this->getMethod()->getTitle() . '<br/>';

if ($this->getInfo()->getLastTransId() == '') {
	echo '<em>' . $this->__('You will be redirected to RayPay website when you place an order.') . '</em>';
}
else {
	echo $this->__('RayPay Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
}
