<?php

/**
 * Magento
 *
 * @category   RayPay
 * @package    RayPay
 * @copyright  Copyright (c) 2021 RayPay (https://raypay.ir)
 */
?>

<center>
    <p><?php echo $this->__('Please wait! You will be redirected to RayPay') ?></p>
</center>
<form id="raypay" action="<?php echo $this->getFormAction(); ?>" method="POST">
<?php if (is_array($this->getFormData())) : ?>
    <?php foreach ($this->getFormData() as $name => $value) : ?>
        <input type="hidden" name="<?php echo $name; ?>" value="<?php echo $value; ?>"/>
    <?php endforeach; ?>
<?php endif; ?>
</form>

<script type="text/javascript">
//<![CDATA[
    var paymentform = document.getElementById('raypay');
    window.onload = paymentform.submit();
//]]>
</script>
